name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ziad-dourbk/workflows/.github/workflows/build.yml@main
    secrets: inherit