name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ziad-dourbk/workflows/.github/workflows/build.yml@main
    with:
      dockerfile: ./Dockerfile
      context: .
